jonse/urls.py
from django.urls import path

from jonse.views import (
    HomeView,
    ListingCreateView,
    ListingDeleteView,
    ListingDetailView,
    MyListingView,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("my/", MyListingView.as_view(), name="my_listings"),
    path("my/listing/create/", ListingCreateView.as_view(), name="listing_create"),
    path("my/listing/<int:pk>/", ListingDetailView.as_view(), name="listing_detail"),
    path(
        "my/listing/<int:pk>/delete/",
        ListingDeleteView.as_view(),
        name="listing_delete",
    ),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("jeonse.urls")),
]

jonse/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from jonse.colors import get_pair


def default_listing_name():
    while True:
        name = get_pair().title()[:200]
        if not Listing.objects.filter(name=name).exists():
            return name


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True)

    deleted_on = models.BooleanField(default=False)

    class Meta:
        abstract = True


class ListingManager(models.Manager):
    def for_home(self):
        return self.filter(deleted_on=False).order_by("-created_at")


# Create your models here.
class Listing(BaseModel):
    NEW = 0
    OK = 1
    OLD = 2

    condition_choices = (
        (NEW, "New"),
        (OK, "OK"),
        (OLD, "Old"),
    )

    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    name = models.CharField(_("Name"), max_length=200, default=default_listing_name)

    jonse_amount = models.BigIntegerField(_("Jonse"), default=0)

    wolse_amount = models.BigIntegerField(_("Wolse"), default=0)

    wolse_rent = models.IntegerField(_("Wolse rent"), default=0)
    gwanlibi = models.IntegerField(_("Management fees"), default=0)

    jonse_interest_rate = models.FloatField(_("Jonse loan interest rate"), default=4)
    jonse_interest_amount_per_month = models.IntegerField(
        _("Jonse loan monthly payment amount"), default=0
    )

    monthly_expense = models.IntegerField(_("Monthly expenses"), default=0)

    number_of_rooms = models.SmallIntegerField(_("# of rooms"), default=1)
    number_of_bathrooms = models.SmallIntegerField(_("# of bathrooms"), default=1)

    condition = models.SmallIntegerField(
        _("Condition"), choices=condition_choices, default=OK
    )

    description = models.TextField(_("Notes"), blank=True)

    objects = ListingManager()

    def save(self, *args, **kwargs):
        self.jonse_interest_amount_per_month = int(
            self.jonse_amount * self.jonse_interest_rate / 100 / 12
        )
        self.monthly_expense = int(
            self.wolse_rent + self.gwanlibi + self.jonse_interest_amount_per_month
        )
        return super().save(*args, **kwargs)

    """
from jonse.models import Listing
Listing.objects.all().delete()
from random import choice

for i in range(1000):
    Listing.objects.create(
        jonse_amount=choice(range(0, 1000000))*i,
        wolse_amount=choice(range(0, 1000000))*i,
        wolse_rent=choice(range(0, 100000))*i,
        gwanlibi=choice(range(0, 100000))*i,
        number_of_rooms=choice(range(1, 10)),
        number_of_bathrooms=choice(range(1, 10)),
        condition=choice(range(0, 3)),
        description=i,
    )
    """

templates/listing/create.html
{% extends "_base.html" %}
{% block main_content %}
    <div class="container pb-5">
        <h1>New listing</h1>
        <p>Add</p>
        <form id="login-form" method="post">
            {% csrf_token %}
            {% include 'listing/form.html' with form=form  %}
            <div class="mt-2 mt-md-3 d-flex justify-content-between">
                <a class="btn btn-outline-danger" href="{% url 'my_listings' %}">Cancel</a>
                <button type="submit" class="btn btn-success">Add</button>
            </div>
        </form>
        <h2 class="mt-4">But why?</h2>
        <p>This is a website to compare different rental options.</p>
        <p>
            With rising loan interest rate and additional fees it is hard to compare multiple <code>Jeonse</code> and
            <code>Wolse</code> options at a glance.
        </p>
        <p>
            This website gives you a simple way to compare <code>Jeonse</code> and <code>Wolse</code> rental options.
        </p>
        <p>
            Main idea is to bring all options to a single <code>Monthly expenses</code> number.
        </p>
        <p>
            <code>Monthly expenses</code> calculated by summing up the <code>Wolse rent</code>, <code>Management fees</code>,
            and <code>Jeonse monthly loan payment amount</code>.
        </p>
        <p>
            Monthly loan payment amount is calculated from the <code>Jeonse</code> deposit amount only. So, this the only
            difference between <code>Jeonse</code> and <code>Wolse</code> deposits in this app. As it is assumed that you
            will get the loan for the <code>Jeonse</code> where as for <code>Wolse</code> you are using your own money.
        </p>
        <p>
            Monthly loan payment amount is calculated by the formula: <code>Jeonse</code> deposit amount *
            <code>Jeonse</code> loan interest rate / 12.
        </p>
        <p>
            If you find yourself not comprehending what the hell I am talking about, please note that it is about housing
            rental options in South Korea. Read for more info: https://en.wikipedia.org/wiki/Jeonse.
        </p>
    </div>
{% endblock %}

templates/listing/delete.html
{% extends "_base.html" %}
{% block main_content %}
    <div class="container pb-5">
        <h1>Delete a listing</h1>
        <p>
            Are you sure you want to delete <code>{{ object.name }}</code> listing?
        </p>
        <form id="login-form" method="post">
            {% csrf_token %}
            <div class="mt-2 mt-md-3 d-flex justify-content-between">
                <a class="btn btn-outline-success"
                   href="{% url 'listing_detail' pk=object.pk %}">Cancel</a>
                <button class="btn btn-danger" type="submit">Delete</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/listing/detail.html
{% extends "_base.html" %}
{% block main_content %}
    {% include "listing/detail_partial.html" %}
{% endblock %}

templates/listing/detail_partial.html
<div class="container pb-5" id="listing-detail">
    <h1>{{ object.name }}</h1>
    <p class="text-break">{{ object.description }}</p>
    <div class="progress my-2">
        <div class="indeterminate"></div>
    </div>
    <div class="my-4">
        <div class="row">
            <h3>Payment Information</h3>
            <div class="col-6">
                <p>Jeonse: {{ object.jeonse_amount }}</p>
            </div>
            <div class="col-6">
                <p>Wolse: {{ object.wolse_amount }}</p>
                <p>Wolse monthly payment: {{ object.wolse_rent }}</p>
            </div>
            <div>
                <p>Management fees (Gwanlibi): {{ object.gwanlibi }}</p>
                <p>Monthly interest payment amount: {{ object.jeonse_interest_amount_per_month }}</p>
                <p class="lead">
                    Total Monthly Expenses: <strong>{{ object.monthly_expense }}</strong>
                </p>
            </div>
        </div>
        <div class="row mt-2">
            <h3>House Information</h3>
            <div class="col-6">
                <p>Rooms / Bathrooms: {{ object.number_of_rooms }} / {{ object.number_of_bathrooms }}</p>
            </div>
            <div class="col-6">
                <p>Condition: {{ object.get_condition_display }}</p>
            </div>
        </div>
        {% if object.jeonse_amount %}
            <div class="row mt-2">
                <h3>Jonse Loan Information</h3>
                <div class="col-6">
                    <p>Jeonse: {{ object.jeonse_amount }}</p>
                    <p>Annual Interest Rate: {{ object.jeonse_interest_rate }}%</p>
                </div>
                <div class="col-6">
                    <p>Annual interest payment amount: {{ object.annual_interest_payment_amount }}</p>
                    <p>Monthly interest payment amount: {{ object.monthly_interest_payment_amount }}</p>
                </div>
            </div>
        {% endif %}
    </div>
    <div class="mt-2 mt-md-3 d-flex justify-content-between">
        <div>
            <a class="btn btn-outline-success" href="{% url 'my_listings' %}">Back</a>
        </div>
        <div>
            <a class="btn btn-outline-danger"
               href="{% url 'listing_delete' pk=object.pk %}">Delete</a>
            <button class="btn btn-success ms-2"
                    hx-target="#listing-detail"
                    hx-get="{% url 'listing_update' pk=object.pk %}"
                    hx-indicator=".progress">
                Edit
            </button>
        </div>
    </div>
</div>
</div>

templates/listing/field.html
{% load widget_tweaks %}
<div class="form-group">
    <span class="fw-bold">{{ field.label_tag }}</span>
    {% if form.is_bound %}
        {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}<div class="invalid-feedback">{{ error }}</div>{% endfor %}
        {% else %}
            {% render_field field class="form-control is-valid" %}
        {% endif %}
    {% else %}
        {% render_field field class="form-control" %}
    {% endif %}
    {% if field.help_text %}<small class="form-text text-muted">{{ field.help_text }}</small>{% endif %}
</div>

templates/listing/form.html
{% load widget_tweaks %}
{% if form %}
    {% for hidden_field in form.hidden_fields %}{{ hidden_field }}{% endfor %}
    {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}{{ error }}{% endfor %}
        </div>
    {% endif %}
    {% for field in form.visible_fields %}
        {% include "listing/field.html" with field=field %}
    {% endfor %}
{% endif %}

templates/listing/update.html
<form hx-post="{% url 'listing_update' pk=object.pk %}">
    {% csrf_token %}
    <h1>{{ object.name }}</h1>
    <p>Edit</p>
    {% include 'listing/form.html' with form=form  %}
    <div class="mt-2 mt-md-3 d-flex justify-content-between">
        <a class="btn btn-outline-danger"
           href="{% url 'listing_detail' pk=object.pk %}">Cancel</a>
        <button type="submit" class="btn btn-success">Save</button>
    </div>
</form>